packages:
  - name: einstore
    parameters:
      SPACES_ENDPOINT: ${SPACES_ENDPOINT}
      SPACES_REGION: ${SPACES_REGION}
      SPACES_BUCKET: ${SPACES_BUCKET}
      SPACES_KEY: ${SPACES_KEY}
      SPACES_SECRET: ${SPACES_SECRET}
    functions:
      - name: ingest
        runtime: nodejs:18
        web: true
        main: main
        limits:
          memory: 1024
          timeout: 300000
