databases:
- engine: PG
  name: db
  version: "17"
domains:
- domain: einstore.pro
  type: PRIMARY
- domain: admin.einstore.pro
  type: ALIAS
- domain: api.einstore.pro
  type: ALIAS
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: api
    match:
      authority:
        exact: api.einstore.pro
      path:
        prefix: /
  - component:
      name: admin
    match:
      authority:
        exact: admin.einstore.pro
      path:
        prefix: /
  - component:
      name: web
    match:
      authority:
        exact: einstore.pro
      path:
        prefix: /
jobs:
- build_command: if [ -n "$BILLING_DEPLOY_KEY" ]; then mkdir -p ~/.ssh && echo "$BILLING_DEPLOY_KEY"
    > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && ssh-keyscan github.com >> ~/.ssh/known_hosts
    && mkdir -p ../Private && git clone git@github.com:Einstore/Billing.git ../Private/billing;
    fi && npm install
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
    value: EV[1:1trs2VkhpvGhCzNDc6Wws/iag2w1Jqnv:TJ2Ghn0Yj0Obzb6K25q35SzQ9aT8mWS7qh/mWUIz7pzmP6BuFU0rxYzvMMxNHvAgQc/UhiTDr//RHng7JcA9hcwKuT9zUIrJvXYj0CvBpsxpvFoGDWIkQTaCVVewxrMJftc23OLbAM/EQicSmk5mutSWBQ2VLvtthMMt+2fXZFHzBlq8xHIFaaMx+rUMxY2zz+VaSCRrVDBlzNwvkXbVwtFwOrg=]
  - key: BILLING_DEPLOY_KEY
    scope: BUILD_TIME
    type: SECRET
    value: EV[1:fecdPnNxziuuXXbcaoeYAcEJDmmsgNlo:HPrZimVW0X9njalAeyeFBXqxiR620+vT3TPznPyGN5zqKWJ1jdo8P0yXm13n4kPnF1lEIvEoFIv0cEeVdzEbBBxTvstrAWPHzPA0cVk0nVV8uw7GXitukMgsVntUoy3VZsGd5P9DPr0dEy07OkwPgVWh4lM7DnI9t5SOF5aqWfV/Oueh+re8CdhqQmfsMQbyszmVqY4WmmpEwLFIdxrrdEfwkSTPGf79hxSGXXZU4MoJYtWUa2Y87dUBLqrZ61g+0m4A3AWvmX+fynThJNvYyrBnYRE84f+FHZxZkAidXLZ1Ct+dtJzkxyK0gv6674uBwgvrGhGCqXlaGcszoSl85XFVafkrj4j4nmthGIK7qHNReyZpHGaPmDguvElNgsUTAISQDo5yxXki8VWMN+t8bSGbHnt8A0jB83OWAgopU1ZM2v8ErCazjiDJitc6T6fT6zzm+Bp03+I5eP4mvkFxJB/Mvh1bjV3jKhj3hF2lrz25Q4wFm+IEY63QCgxfzyKhd9eLEAOFCLLjfzw2vppt1HQNum5nMmjQ0lja01nMh8og2YxDdECw5pNSlw==]
  - key: NPM_CONFIG_INSTALL_LINKS
    scope: BUILD_TIME
    value: "false"
  environment_slug: node-js
  github:
    branch: main
    repo: Einstore/Einstore
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  kind: PRE_DEPLOY
  name: prisma-migrate
  run_command: npm run prisma:deploy
  source_dir: /API
name: einstore
region: lon
services:
- build_command: if [ -n "$BILLING_DEPLOY_KEY" ]; then mkdir -p ~/.ssh && echo "$BILLING_DEPLOY_KEY"
    > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && ssh-keyscan github.com >> ~/.ssh/known_hosts
    && mkdir -p ../Private && git clone git@github.com:Einstore/Billing.git ../Private/billing;
    fi && npm --prefix ../Libraries/rafiki-auth install && npm --prefix ../Libraries/rafiki-auth
    run build && rm -rf node_modules/@unlikeother/auth/dist && mkdir -p node_modules/@unlikeother/auth/dist
    && cp -R ../Libraries/rafiki-auth/dist/* node_modules/@unlikeother/auth/dist/
    && npm --prefix ../Libraries/teams install && npm --prefix ../Libraries/teams
    run build && rm -rf node_modules/@rafiki270/teams/dist && mkdir -p node_modules/@rafiki270/teams/dist
    && cp -R ../Libraries/teams/dist/* node_modules/@rafiki270/teams/dist/ && npm
    run prisma:generate && npm run build
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
    value: EV[1:1trs2VkhpvGhCzNDc6Wws/iag2w1Jqnv:TJ2Ghn0Yj0Obzb6K25q35SzQ9aT8mWS7qh/mWUIz7pzmP6BuFU0rxYzvMMxNHvAgQc/UhiTDr//RHng7JcA9hcwKuT9zUIrJvXYj0CvBpsxpvFoGDWIkQTaCVVewxrMJftc23OLbAM/EQicSmk5mutSWBQ2VLvtthMMt+2fXZFHzBlq8xHIFaaMx+rUMxY2zz+VaSCRrVDBlzNwvkXbVwtFwOrg=]
  - key: SPACES_ENDPOINT
    scope: RUN_TIME
    value: https://lon1.digitaloceanspaces.com
  - key: SPACES_REGION
    scope: RUN_TIME
    value: lon1
  - key: SPACES_BUCKET
    scope: RUN_TIME
    value: einstore
  - key: SPACES_KEY
    scope: RUN_TIME
    type: SECRET
    value: EV[1:Bnd9dlhgqxxCgE5fXBkyc6Y+7x2EzUup:mc8YoFne5QBCV9xRPYpFOc7jFPsJrGMt6/vDQjm5gDDXeDsd]
  - key: SPACES_SECRET
    scope: RUN_TIME
    type: SECRET
    value: EV[1:fd8+yzvlF7vd/05qq7ueHFaR8LnDLrkA:uiX2d/K07pldbBnahamt9GTCG1JVajRQWN3TLyyXv1DYeXpuNvWCauJ3yuF/FJNCfkdJEyqRup6L4pM=]
  - key: GOOGLE_CLIENT_ID
    scope: RUN_TIME
    value: 49313448856-rrlpvcg18e8m628rkqn3s10ilke6lpn3.apps.googleusercontent.com
  - key: GOOGLE_CLIENT_SECRET
    scope: RUN_TIME
    type: SECRET
    value: EV[1:f9rHoA7RMEUo3M1JSB8+uRA1SYAa9K6y:4nI0GudTOL0HOKsHOLlSopRQGorx/uAopbgFgvgveOzft48WHUyEmGpDquIgA0NoBuas]
  - key: GOOGLE_REDIRECT_URI
    scope: RUN_TIME
    value: https://api.einstore.pro/auth/oauth/google/callback
  - key: AUTH_JWT_SECRET
    scope: RUN_TIME
    type: SECRET
    value: EV[1:YfqHHTyx+SCMRz+bXUUd6xGfhwmgPT+0:cVzQmkJoUhqRnCNikNOybgI2TJbvxaufoRG0auAaFraPRRTePxEQrF26FN9ClGXoQr1y5HMRpqC/jgzZjpNlpV3XBCf+uXZ1ITFOiVz+WTI=]
  - key: AUTH_JWT_ISSUER
    scope: RUN_TIME
    value: einstore
  - key: AUTH_JWT_AUDIENCE
    scope: RUN_TIME
    value: einstore-api
  - key: AUTH_REFRESH_TTL_DAYS
    scope: RUN_TIME
    value: "30"
  - key: AUTH_ACCESS_TTL_MINUTES
    scope: RUN_TIME
    value: "15"
  - key: API_KEY_SECRET
    scope: RUN_TIME
    type: SECRET
    value: EV[1:pEztCa5UhQNMV5ErTqLjVtUwciUDiBrB:/YNfXpW5qGOcSbvEMIj79vIDWGW3w4Go4+i5GPF8iUtb]
  - key: BILLING_DEPLOY_KEY
    scope: BUILD_TIME
    type: SECRET
    value: EV[1:fecdPnNxziuuXXbcaoeYAcEJDmmsgNlo:HPrZimVW0X9njalAeyeFBXqxiR620+vT3TPznPyGN5zqKWJ1jdo8P0yXm13n4kPnF1lEIvEoFIv0cEeVdzEbBBxTvstrAWPHzPA0cVk0nVV8uw7GXitukMgsVntUoy3VZsGd5P9DPr0dEy07OkwPgVWh4lM7DnI9t5SOF5aqWfV/Oueh+re8CdhqQmfsMQbyszmVqY4WmmpEwLFIdxrrdEfwkSTPGf79hxSGXXZU4MoJYtWUa2Y87dUBLqrZ61g+0m4A3AWvmX+fynThJNvYyrBnYRE84f+FHZxZkAidXLZ1Ct+dtJzkxyK0gv6674uBwgvrGhGCqXlaGcszoSl85XFVafkrj4j4nmthGIK7qHNReyZpHGaPmDguvElNgsUTAISQDo5yxXki8VWMN+t8bSGbHnt8A0jB83OWAgopU1ZM2v8ErCazjiDJitc6T6fT6zzm+Bp03+I5eP4mvkFxJB/Mvh1bjV3jKhj3hF2lrz25Q4wFm+IEY63QCgxfzyKhd9eLEAOFCLLjfzw2vppt1HQNum5nMmjQ0lja01nMh8og2YxDdECw5pNSlw==]
  - key: CORS_ORIGINS
    scope: RUN_TIME
    value: https://admin.einstore.pro,https://einstore.pro,http://localhost:8081,http://localhost:5173
  - key: NPM_CONFIG_INSTALL_LINKS
    scope: BUILD_TIME
    value: "false"
  github:
    branch: main
    repo: Einstore/Einstore
  health_check:
    http_path: /health
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: api
  run_command: npm run start
  source_dir: /API
static_sites:
- github:
    branch: main
    repo: Einstore/Einstore
  index_document: index.html
  name: web
  output_dir: .
  source_dir: /Web
- build_command: if [ -n "$BILLING_DEPLOY_KEY" ]; then mkdir -p ~/.ssh && echo "$BILLING_DEPLOY_KEY"
    > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && ssh-keyscan github.com >> ~/.ssh/known_hosts
    && mkdir -p ../Private && git clone git@github.com:Einstore/Billing.git ../Private/billing;
    fi && npm install && npm run build
  envs:
  - key: VITE_API_BASE_URL
    scope: BUILD_TIME
    value: https://api.einstore.pro
  - key: BILLING_DEPLOY_KEY
    scope: BUILD_TIME
    type: SECRET
    value: EV[1:fILF5dkPCsheR/h2IgD2JmCSJhpaXAlM:rO7EEKtEF1GPAmkZPFSyhaTZLG+lK2OfFLCe+kfMysBO+/IiONmzCSsfuB9uR34VP3HbaKSGfiiykxNua10R5qjwjY5DSJx6e8OzwCI2T5bomzLsnML+svBkoA/N4WDaWh1tXB6oOtcFGGxq/xJ78vuV0kEAmmhNTJG73bQmsByI7KEjIgfsDwFtfUsyDtCpoH4vMqYX+CZter3Mql5sRuDLZKW+MfZvFu0VKpose3JeVu0bOCcirW6LkaFuIC6995z1tcaxklxopMyQ6WHOVfy03Jf+El5vvAx8umooWbUebhRKGPKp8aH+JCSA0K7d64EQaB+1SepAn4k6a55648YVYhz8Wb31Y/awZGVFlshvuypBj+5lGYJD5RZNgl5+kqGl1YZpn9DQ6xwu1v7jn9tEd1mJkFlxcX04gxvZOMQR8/PyJxUspX49YsAkrLWY4Off9pI28BtuoDpXZrsgaVivq11t7aEAxolRZoZExpEgw83YRqqrUBoaNWylCoT31gOzdphPYmlNpKvhvnxXFD2Oi2ISnpcIfYgwjp9BfbQ+lSwtSnUgvqcwJA==]
  github:
    branch: main
    repo: Einstore/Einstore
  name: admin
  output_dir: dist
  source_dir: /Admin
