version: '2.4'

services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: einstore
      POSTGRES_PASSWORD: einstore
      POSTGRES_DB: einstore
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: michalhosna/adminer:master
    environment:
      ADMINER_DRIVER: pgsql
      ADMINER_SERVER: postgres
      ADMINER_DB: einstore
      ADMINER_USERNAME: einstore
      ADMINER_PASSWORD: einstore
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: einstore

  api:
    image: einstore/einstore-core:dev.master.debug
    restart: on-failure
    environment:
      APICORE_STORAGE_LOCAL_ROOT: /home/einstore

      APICORE_SERVER_NAME: "Einstore - Enterprise AppStore"
      APICORE_SERVER_PATH_PREFIX: ~
      APICORE_SERVER_MAX_UPLOAD_FILESIZE: 50

      APICORE_DATABASE_HOST: postgres
      APICORE_DATABASE_USER: einstore
      APICORE_DATABASE_PASSWORD: einstore
      APICORE_DATABASE_DATABASE: einstore
      APICORE_DATABASE_PORT: 5432
      APICORE_DATABASE_LOGGING: 'false'

      APICORE_STORAGE_S3_ENABLED: 'false'
      APICORE_STORAGE_S3_BUCKET: ~
      APICORE_STORAGE_S3_ACCESS_KEY: ~
      APICORE_STORAGE_S3_REGION: ~
      APICORE_STORAGE_S3_SECRET_KEY: ~

      APICORE_JWT_SECRET: secret
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -q http://localhost:8080/$${APICORE_SERVER_PATH_PREFIX}/info"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  admin:
    image: einstore/einstore-admin:0.1.0

volumes:
  pgsql-data: ~
