// Auto-generated by scripts/prepare-private.mjs. Do not edit by hand.
declare module "../../../Private/billing/api/index.js" {
  import type { FastifyInstance } from "fastify";
  import type { PrivateApiPluginDeps } from "./types.js";
  export function register(app: FastifyInstance, deps: PrivateApiPluginDeps): Promise<void> | void;
  const _default: typeof register;
  export default _default;
}
